sudo: required
language: php

php:
  - 7.1

services:
  - mysql

# Only watch the master branch and tagged release.
branches:
 only:
   - master
   - develop
   - stage
   - /^v\d+\.\d+(\.\d+)?(-\S*)?$/

before_install:
## MySQL 5.7 Install
  - travis_retry sudo apt-key adv --keyserver pgp.mit.edu --recv-keys 5072E1F5
  - echo mysql-apt-config mysql-apt-config/select-server select mysql-5.7 | sudo debconf-set-selections
  - wget http://dev.mysql.com/get/mysql-apt-config_0.8.6-1_all.deb
  - sudo DEBIAN_FRONTEND=noninteractive dpkg -i mysql-apt-config_0.8.6-1_all.deb
  - sudo apt-get update -q
  - sudo apt-get install -q -y -o Dpkg::Options::=--force-confnew mysql-server
  - sudo mysql_upgrade --force
## End MySQL 5.7 Install

before_script:
  - mysql -u root -e 'CREATE DATABASE homestead_test;'
    mysql -u root -e "CREATE USER 'homestead'@'localhost' IDENTIFIED BY
    'secret';"
  - mysql -u root -e "GRANT ALL ON homestead_test.* TO 'homestead'@'localhost';"
  - cp .env.travis .env
  - composer self-update
  - composer clear-cache -vvv
  - composer install --no-interaction -vvv
  - composer dump-autoload -vvv
  - php artisan migrate:refresh --seed

script:
  - ./vendor/bin/phpunit
