runtime: php
env: flex

runtime_config:
  document_root: public

# Ensure we skip ".env", which is only for local development
skip_files:
  - .env
  - vendor/

env_variables:
  # Put production environment variables here.
  APP_LOG: errorlog
  APP_KEY: base64:/G+V/4bO6TRCfNYiI5WKEqVbuy+bmL7hSEVyHFKUKjc=
  STORAGE_DIR: /tmp
